tabuada = int(input('Qual tabuada deseja?'))

print('{} X {} = {}'.format(tabuada, 1, tabuada*1))
print('{} X {} = {}'.format(tabuada, 2, tabuada*2))
print('{} X {} = {}'.format(tabuada, 3, tabuada*3))
print('{} X {} = {}'.format(tabuada, 4, tabuada*4))
print('{} X {} = {}'.format(tabuada, 5, tabuada*5))
print('{} X {} = {}'.format(tabuada, 6, tabuada*6))
print('{} X {} = {}'.format(tabuada, 7, tabuada*7))
print('{} X {} = {}'.format(tabuada, 8, tabuada*8))
print('{} X {} = {}'.format(tabuada, 9, tabuada*9))
print('{} X {} = {}'.format(tabuada, 10, tabuada*10))